// <auto-generated />
namespace Overtime.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201504101542351_Initialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201504101542351_Initialization));
        
        string IMigrationMetadata.Id
        {
            get { return "201504242046187_201504101542351_Initialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
